markdown: kramdown
encoding: UTF-8
permalink: date
gems: [jekyll-paginate]
paginate: 3
highlighter: rouge
lsi: false


# This is a german blog...
kramdown:
  smart_quotes:   sbquo,lsquo,bdquo,ldquo

sharing :
  twitter :
    size :
    via :
    count :
  facebook :
    appid : 205602882797935 # FIXME HARD
    layout : button_count
    font :
    faces : false
    width : 90
  googleplus :
    size : medium
    width :
    annotation : bubble
  linkedin :
    counter : right

authors:
  michael-sperber:
    name: Michael Sperber
    image: /author/michael-sperber.jpg
    href: "http://www.active-group.de/unternehmen/sperber.html"
    about: '<a href="http://www.active-group.de/unternehmen/sperber.html">Dr. Michael Sperber</a> ist Geschäftsführer der <a href="http://www.active-group.de/">Active Group GmbH</a> und international anerkannter Spezialist für alle Aspekte der funktionalen Programmierung.'
  stefan-wehr:
    name: Stefan Wehr
    image: /author/stefan-wehr.jpg
    href: "http://www.factisresearch.com/company.html#swehr"
    about: '<a href="http://www.factisresearch.com/company.html#swehr">Dr. Stefan Wehr</a> entwirft und entwickelt bei der <a href="http://www.factisresearch.com">factis research GmbH</a> komplexe Anwendungen sowohl in klassischen als auch in funktionalen Sprachen. Er ist international anerkannter Spezialist für funktionale Programmierung.'
  david-frese:
    name: David Frese
    image: /author/david-frese.jpg
    href: "http://www.active-group.de/unternehmen/frese.html"
    about: '<a href="http://www.active-group.de/unternehmen/frese.html">David Frese</a> ist Softwarearchitekt bei der <a href="http://www.active-group.de/">Active Group GmbH</a>, Diplom-Informatiker, und verfügt über langjährige Erfahrung in funktionaler aber auch klassischer Programmierung in großen Projekten der Industrie.'
  andreas-bernauer:
    name: Andreas Bernauer
    image: /author/andreas-bernauer.jpg
    about: '<a href="http://www.active-group.de/unternehmen/bernauer.html">Dr. Andreas Bernauer</a> ist Software-Architekt bei der <a href="http://www.active-group.de/">Active Group GmbH</a> und beschäftigt sich seit über 10 Jahren mit funktionaler Programmierung.'
  uwe-schmidt:
    name: Uwe Schmidt
    image: /author/uwe-schmidt.jpg
    href: "http://www.fh-wedel.de/~si/"
    about: '<a href="http://www.fh-wedel.de/~si/">Prof. Dr. Uwe Schmidt</a> lehrt an der <a href="http://www.fh-wedel.de">FH Wedel</a> im Fachbereich Informatik Programmiersprachen und Software-Entwicklung, unter anderem seit dem Jahr 2000 <em>Funktionale Programmierung mit Haskell</em> im Master-Studiengang für Informatik. Er ist Autor des bekannten Haskell Pakets <a href="http://www.fh-wedel.de/~si/HXmlToolbox/index.html">HXT</a>, eine standardkonforme und sehr umfangreiche Bibliothek zur XML-Verarbeitung.'
  alexander-thiemann:
    name: Alexander Thiemann
    image: /author/alexander-thiemann.jpg
    href: "http://www.factisresearch.com/company.html#nthiemann"
    about: '<a href="http://www.factisresearch.com/company.html#athiemann">Alexander Thiemann</a> entwirft und entwickelt bei der <a href="http://www.factisresearch.com">factis research GmbH</a> &uuml;berwiegend Webanwendungen.'
  niklas-baumstark:
    name: Niklas Baumstark
    href: "http://www.factisresearch.com/company.html#nbaumstark"
    about: '<a href="http://www.factisresearch.com/company.html#nbaumstark">Niklas Baumstark</a> entwickelt neben seinem Studium Software bei der <a href="http://www.factisresearch.com">factis research GmbH</a> im funktionalen Paradigma. Zu seinen Spezialgebieten zählen systemnahe Programmierung und Algorithmen.'
  joachim-breitner:
    name: Joachim Breitner
    image: /author/joachim-breitner.png
    href: "http://www.joachim-breitner.de/blog/"
    about: '<a href="http://www.joachim-breitner.de/">Joachim Breitner</a> ist Doktorand am Karlsruher Institut für Technologie und forscht zur Semantik von Bedarfsauswertung. Seit 8 Jahren programmiert er Haskell und engagiert sich in der Community, etwa als GHC-Entwickler und als Mitglied des Haskell Core Library Committees.'
  johannes-weiss:
    name: Johannes Weiß
    image: /author/johannes-weiss.png
    href: "http://www.johannesweiss.eu/"
    about: '<a href="http://johannesweiss.eu/">Johannes Weiß</a> arbeitet bei <a href="http://www.bromium.com/">Bromium</a>, einem vielversprechendem IT-Sicherheits-Startup in Cambridge, UK. Seit längerer Zeit interessiert er sich unter anderem für funktionale Programmiersprachen, insbesondere Haskell.'
  ingo-wechsung:
    name: Ingo Wechsung
    href: "http://www.contexo.de/"
    about: 'Ingo Wechsung arbeitet als IT-Berater für die Firma contexo GmbH in Reutlingen.'
  torsten-grust:
    name: Torsten Grust
    image: /author/torsten-grust.png
    href: "http://db.inf.uni-tuebingen.de/team/grust/"
    about: '<a href="http://db.inf.uni-tuebingen.de/team/grust/">Torsten Grust</a> ist Professor für Datenbanksysteme an der Universität Tübingen. Torsten ist am glücklichsten, wenn er in seiner Forschung Ideen aus der Welt der Datenbanksysteme und der funktionalen Programmierung mischen kann.'
  helmut-dobretzberger:
    name: Helmut Dobretzberger
    image: /author/helmut-dobretzberger.jpg
    about: 'Helmut Dobretzberger ist seit 2003 Softwareentwickler, und bringt Projekte bei der <a href="http://www.active-group.de">Active Group</a> mit Hilfe funktionaler Programmierung voran.'
  andres-loeh:
    name: Andres Löh
    image: /author/andres-loeh.jpg
    href: "http://www.andres-loeh.de"
    about: '<a href="http://www.andres-loeh.de/">Dr. Andres Löh</a> ist Partner bei <a href="http://www.well-typed.com/">Well-Typed LLP</a>, einer auf Haskell spezialisierten Software-Beratungsfirma. Andres verwendet Haskell seit 1997.'
  matthias-fischmann:
    name: Matthias Fischmann
    image: /author/matthias-fischmann.jpg
    href: "http://zerobuzz.net/"
    about: 'Dr. Matthias Fischmann ist Geschäftsführer und Senior Consultant bei <a href="http://zerobuzz.net/">zerobuzz.net</a>, einem Beratungsunternehmen mit den Standbeinen SAP und Haskell.  Er arbeitet seit 1999 mit Haskell und anderen funktionalen Sprachen.'
  david-leuschner:
    name: David Leuschner
    image: /author/david-leuschner.jpg
    about: 'David Leuschner ist Geschäftsführer und Entwicklungsleiter der <a href="http://factisresearch.com">factis research GmbH</a>. Er setzt sich seit mehr als 10 Jahren für den Einsatz funktionaler Sprachen in der Industrie ein.'
  emin-karayel:
    name: Emin Karayel
    image: /author/emin-karayel.png
    href: "https://de.linkedin.com/pub/emin-karayel/28/774/524"
    about: '<a href="https://de.linkedin.com/pub/emin-karayel/28/774/524">Emin Karayel</a> hat Mathematik am KIT studiert, verfügt über mehr als 10 Jahre Erfahrung in der Software-Technik und entwickelt bei der <a href="http://www.factisresearch.com">factis research GmbH</a> verteilte Anwendungen und Machine-Learning Algorithmen unter anderem mit Haskell.'
  alex-gremm:
    name: Alexandros Gremm
    image: /author/alex-gremm.png
    about: 'Alexandros Gremm hat einen Master-Abschluss in Informatik von der Universität Tübingen. Sein besonderes Interesse gilt dem High-Performance-Computing in der Funktionalen Programmierung, insbesondere in Haskell.'
  dierk-koenig:
    name: Dierk König
    image: /author/dierk-koenig.jpg
    href: "http://www.canoo.com"
    about: 'Dierk König ist Fellow bei der Canoo AG, Basel, und trägt zu den Projekten Frege, OpenDolphin, Groovy, Grails, GPars, GroovyFX und Canoo WebTest bei. Er ist Hauptautor des Beststellers <a href="https://github.com/Dierk/GroovyInAction">Groovy in Action</a>. Twitter: @mittie'
  marcus-crestani:
    name: Marcus Crestani
    image: /author/marcus-crestani.png
    href: "http://www.active-group.de/unternehmen/crestani.html"
    about: '<a href="http://www.active-group.de/unternehmen/crestani.html">Marcus Crestani</a> ist Software-Architekt bei der <a href="http://www.active-group.de/">Active Group GmbH</a> und hat langjährige Erfahrung in funktionaler Programmierung, Softwarearchitektur und Programmiersprachen.'
  marco-schneider:
    name: Marco Schneider
    image: /author/marco-schneider.jpg
    href: "https://twitter.com/eskape"
    about: 'Marco Schneider ist seit Abschluss (M.Sc., in Medieninformatik) seines Studiums an der Universität Tübingen Software-Architekt bei der <a href="http://www.active-group.de/">Active Group GmbH</a>. Sein besonderes Interesse gilt der funktionalen Programmierung und der künstlichen Intelligenz.'
  simon-schulz:
    name: Simon Schulz
    image: /author/simon-schulz.jpeg
    href:
    about: 'Simon Schulz ist Software-Architekt bei der <a href="http://www.active-group.de/">Active Group GmbH</a>. Sein besonderes Interesse gilt der funktionalen Programmierung und Softwarearchitektur.'
  tim-digel:
    name: Tim Digel
    image: /author/tim-digel.jpg
    href:
    about: 'Tim Digel hat einen Abschluss als Diplom Mathematiker und ist seither als Software-Architekt bei der <a href="http://www.active-group.de/">Active Group GmbH</a> tätig. Sein besonderes Interesse gilt der Systemintegration und -administration.'

